maps/extended.cfg
maps/extended.res
maps/extended_motd.txt
maps/extended_readme.txt
sound/extended/keycode1.wav
sound/extended/keycode2.wav
sound/extended/papers.wav
sound/extended/tankmove.wav
sound/extended/tankstart.wav
extension.wad