maps/sc_greysnake1.cfg
maps/sc_greysnake1.res
maps/sc_greysnake1_motd.txt
maps/sc_greysnake1_skl.cfg
models/greysnake/eskiemo.mdl
models/greysnake/hgrunt_medic.mdl
models/greysnake/hgrunt_opfor.mdl
models/greysnake/massn.mdl
models/greysnake/snow_turret.mdl
models/greysnake/snow_turretT.mdl
models/greysnake/voltorsnow.mdl
