// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/detail/crystal_mission/flr01_detail.tga
gfx/detail/crystal_mission/flr4c_detail.tga
gfx/detail/crystal_mission/rock_detail.tga
gfx/detail/crystal_mission/rockfloor_detail.tga
gfx/detail/crystal_mission/wall3a_detail.tga
gfx/detail/crystal_mission/wall3g_detail.tga
gfx/env/deserttcm_bk.tga
gfx/env/deserttcm_dn.tga
gfx/env/deserttcm_ft.tga
gfx/env/deserttcm_lf.tga
gfx/env/deserttcm_rt.tga
gfx/env/deserttcm_up.tga
maps/sv_crystal_mission_1a_detail.txt
models/crystal_mission/5ton.mdl
models/crystal_mission/banc.mdl
models/crystal_mission/batiment.mdl
models/crystal_mission/batiment2.mdl
models/crystal_mission/box.mdl
models/crystal_mission/canape.mdl
models/crystal_mission/canette.mdl
models/crystal_mission/grille.mdl
models/crystal_mission/montagne.mdl
models/crystal_mission/montagne2big.mdl
models/crystal_mission/montagne3.mdl
models/crystal_mission/montagne5big.mdl
models/crystal_mission/montagne_bis.mdl
models/crystal_mission/mug.mdl
models/crystal_mission/note.mdl
models/crystal_mission/poubelle.mdl
models/crystal_mission/sacs.mdl
models/crystal_mission/table.mdl
sound/crystal_mission/beep.ogg
sound/crystal_mission/beep_key.ogg
sound/crystal_mission/coin.ogg
sound/crystal_mission/machine_ambient.wav
sound/crystal_mission/machine_coffee.ogg
sound/crystal_mission/materials.txt
sound/crystal_mission/soda.ogg
sound/crystal_mission/wind.ogg
sprites/crystal_mission/wind.spr
sprites/crystal_mission/wind2.spr
