// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/detail/crystal_mission/flr01_detail.tga
gfx/detail/crystal_mission/flr4c_detail.tga
gfx/env/deserttcm2_bk.tga
gfx/env/deserttcm2_dn.tga
gfx/env/deserttcm2_ft.tga
gfx/env/deserttcm2_lf.tga
gfx/env/deserttcm2_rt.tga
gfx/env/deserttcm2_up.tga
maps/sv_crystal_mission_4a_detail.txt
models/crystal_mission/banc.mdl
models/crystal_mission/box_lab.mdl
models/crystal_mission/cafetiere.mdl
models/crystal_mission/camera.mdl
models/crystal_mission/canape.mdl
models/crystal_mission/canard.mdl
models/crystal_mission/canette.mdl
models/crystal_mission/canette2.mdl
models/crystal_mission/chaise.mdl
models/crystal_mission/chaise_bureau.mdl
models/crystal_mission/chariot.mdl
models/crystal_mission/corbeille.mdl
models/crystal_mission/crystal.mdl
models/crystal_mission/ecran.mdl
models/crystal_mission/lavabo.mdl
models/crystal_mission/mug.mdl
models/crystal_mission/mug2.mdl
models/crystal_mission/nettoyage.mdl
models/crystal_mission/nettoyage2.mdl
models/crystal_mission/note.mdl
models/crystal_mission/plante.mdl
models/crystal_mission/poster2.mdl
models/crystal_mission/souris.mdl
models/crystal_mission/table.mdl
models/crystal_mission/table_manger.mdl
models/crystal_mission/tabouret.mdl
models/crystal_mission/verre.mdl
sound/crystal_mission/beep.ogg
sound/crystal_mission/beep_key.ogg
sound/crystal_mission/coin.ogg
sound/crystal_mission/duck.wav
sound/crystal_mission/machine_ambient.wav
sound/crystal_mission/machine_coffee.ogg
sound/crystal_mission/materials.txt
sound/crystal_mission/soda.ogg
