// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/detail/crystal_mission/flr01_detail.tga
gfx/detail/crystal_mission/flr4c_detail.tga
gfx/detail/crystal_mission/rock_detail.tga
gfx/detail/crystal_mission/rockfloor_detail.tga
gfx/detail/crystal_mission/wall3a_detail.tga
gfx/detail/crystal_mission/wall3g_detail.tga
gfx/env/deserttcm2_bk.tga
gfx/env/deserttcm2_dn.tga
gfx/env/deserttcm2_ft.tga
gfx/env/deserttcm2_lf.tga
gfx/env/deserttcm2_rt.tga
gfx/env/deserttcm2_up.tga
maps/sv_crystal_mission_2a_detail.txt
models/crystal_mission/5ton.mdl
models/crystal_mission/banc.mdl
models/crystal_mission/batiment.mdl
models/crystal_mission/box_apdd.mdl
models/crystal_mission/canette.mdl
models/crystal_mission/canette2.mdl
models/crystal_mission/chaise.mdl
models/crystal_mission/chaise_bureau.mdl
models/crystal_mission/cookie_plat.mdl
models/crystal_mission/corbeille.mdl
models/crystal_mission/ecran.mdl
models/crystal_mission/lavabo.mdl
models/crystal_mission/montagne2.mdl
models/crystal_mission/montagne2big.mdl
models/crystal_mission/montagne5.mdl
models/crystal_mission/montagne_bis.mdl
models/crystal_mission/mug.mdl
models/crystal_mission/note.mdl
models/crystal_mission/plante.mdl
models/crystal_mission/poubelle.mdl
models/crystal_mission/sacs.mdl
models/crystal_mission/souris.mdl
models/crystal_mission/suv.mdl
models/crystal_mission/table_manger.mdl
sound/crystal_mission/beep.ogg
sound/crystal_mission/beep_key.ogg
sound/crystal_mission/coin.ogg
sound/crystal_mission/machine_ambient.wav
sound/crystal_mission/machine_coffee.ogg
sound/crystal_mission/materials.txt
sound/crystal_mission/soda.ogg
