// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/detail/crystal_mission/flr01_detail.tga
gfx/detail/crystal_mission/flr4c_detail.tga
gfx/env/deserttcm2_bk.tga
gfx/env/deserttcm2_dn.tga
gfx/env/deserttcm2_ft.tga
gfx/env/deserttcm2_lf.tga
gfx/env/deserttcm2_rt.tga
gfx/env/deserttcm2_up.tga
maps/sv_crystal_mission_3a_detail.txt
models/crystal_mission/banc.mdl
models/crystal_mission/box.mdl
models/crystal_mission/box_lab.mdl
models/crystal_mission/cafetiere.mdl
models/crystal_mission/camera.mdl
models/crystal_mission/canape.mdl
models/crystal_mission/canette.mdl
models/crystal_mission/canette2.mdl
models/crystal_mission/card.mdl
models/crystal_mission/chaise.mdl
models/crystal_mission/chaise_bureau.mdl
models/crystal_mission/chariot.mdl
models/crystal_mission/chariot_mini.mdl
models/crystal_mission/cookie_plat.mdl
models/crystal_mission/corbeille.mdl
models/crystal_mission/ecran.mdl
models/crystal_mission/lavabo.mdl
models/crystal_mission/microscope.mdl
models/crystal_mission/mug.mdl
models/crystal_mission/mug2.mdl
models/crystal_mission/nettoyage.mdl
models/crystal_mission/note.mdl
models/crystal_mission/plante.mdl
models/crystal_mission/poster.mdl
models/crystal_mission/sacs2.mdl
models/crystal_mission/souris.mdl
models/crystal_mission/table.mdl
models/crystal_mission/table_manger.mdl
models/crystal_mission/tabouret.mdl
models/crystal_mission/verre.mdl
sound/blackops/ambience/mtl_break.wav
sound/crystal_mission/beep.ogg
sound/crystal_mission/beep_key.ogg
sound/crystal_mission/card.ogg
sound/crystal_mission/coin.ogg
sound/crystal_mission/come_get_some.wav
sound/crystal_mission/duke.wav
sound/crystal_mission/machine_ambient.wav
sound/crystal_mission/machine_coffee.ogg
sound/crystal_mission/materials.txt
sound/crystal_mission/soda.ogg
sprites/crystal_mission/laser_scan.spr
